# Generated by Django 6.0.4 on 2026-04-25 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('especialidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Especialidade')),
                ('crm', models.CharField(max_length=20, verbose_name='CRM')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('valor', models.FloatField(blank=True, default=None, null=True, verbose_name='Valor')),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(verbose_name='Data da Consulta')),
                ('Observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exemplo02.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exemplo02.paciente', verbose_name='Paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exemplo02.procedimento', verbose_name='Procedimento')),
            ],
            options={
                'ordering': ['-data_consulta'],
            },
        ),
    ]
