# Generated by Django 6.0.4 on 2026-04-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo01', '0003_alter_pessoa_options_pessoa_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descricao')),
                ('cid', models.CharField(max_length=20, verbose_name='CID')),
                ('valor', models.FloatField(blank=True, default=None, null=True, verbose_name='Valor')),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='procedimento_executado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(max_length=50, verbose_name='Obs')),
                ('quantidade', models.FloatField(blank=True, default=None, null=True, verbose_name='Quantidade')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exemplo01.pessoa')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exemplo01.procedimento')),
            ],
            options={
                'ordering': ['pessoa', 'procedimento'],
            },
        ),
    ]
